package services

import (
	"database/sql"
	"fmt"
	"log"

	help "github.com/Max-Jordan/ArticlesBot/bot"
	"github.com/Max-Jordan/ArticlesBot/lib/e"
)

type PostgreStorage struct {
	db *sql.DB
}

func NewStorage(db *sql.DB) *PostgreStorage {
	createArticleTable(db)
	return &PostgreStorage{db: db}
}

func (pS *PostgreStorage) Save(article *Article) error {
	query := `insert into articles(
	user_id, url, description, completed) 
	values ($1, $2, $3, $4)`
	_, err := pS.db.Exec(query, article.UserId, article.URL, article.Description, article.Readed)
	if err != nil {
		return nil
	}
	return nil
}

func (pS *PostgreStorage) List(userId int64) ([]Article, error) {
	list := make([]Article, 0, 5)
	query := `select * from articles where user_id = $1`
	rows, err := pS.db.Query(query, userId)
	if err != nil {
		log.Println(e.Wrap("Getting articles error", err))
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		article := Article{}
		if err := rows.Scan(
			&article.Id, &article.UserId,
			&article.URL, &article.Description,
			&article.Readed); err != nil {
			log.Print(err)
			return nil, err
		}
		if err = rows.Err(); err != nil {
			return nil, nil
		}
		list = append(list, article)
	}
	return list, nil
}

func createArticleTable(db *sql.DB) {
	query := `create table if not exists articles(
	id bigint generated by default as identity primary key,
	user_id bigint not null,
	url varchar(250) not null,
	description varchar(250),
	completed bool)`
	_, err := db.Exec(query)
	if err != nil {
		log.Fatal("Creating article table error", err)
	}
}

type Article struct {
	Id          int64  `json:"id"`
	UserId      int64  `json:"user_id"`
	URL         string `json:"url"`
	Description string `json:"description"`
	Readed      bool   `json:"readed"`
}

func NewArticle(URL string, description string) *Article {
	return &Article{
		URL:         URL,
		Description: description,
		Readed:      false,
	}
}

func NewEptyArticle() *Article {
	return &Article{}
}

func (a Article) ToString() string {
	var flag string
	if a.Readed {
		flag = "Прочитано"
	} else {
		flag = "Не прочитано"
	}
	return fmt.Sprintf(
		`*URL:* %s *Описание:* %s *Статус:* %s`+"\n",
		help.EscapeMarkdownV2(a.URL),
		help.EscapeMarkdownV2(a.Description),
		help.EscapeMarkdownV2(flag))
}

func (a *Article) Complete() {
	a.Readed = true
}
